### ISSUE TITLE
Why was this abandoned?

### ISSUE THREAD

**Issue by raulsebastianmihaila** [dslomov/typed-objects-es7#16]
According to this [list](https://github.com/tc39/proposals/blob/master/inactive-proposals.md), this proposal was abandoned. Why?

**Comment by kgryte** [comment]
I would also like to know if, and why, this proposal was abandoned. Typed-objects would be a great addition to ES, including for serialization, as a gateway for user-defined types, etc.

**Comment by ashnur** [comment]
Because having a class keywords was more easily agreed on afaik. I am waiting for this since 2012. This is actually something that would allow the browser to do complicated AND fast stuff if someone wants to write the details. Right now TypedArrays are not providing the necessary benefits in terms of speed.

**Comment by quantuminformation** [comment]
I don't bother with classes anymore, they are fluff to me, good old prototype!

**Comment by dslomov** [comment]
Sorry for late reply - neither I no @nikomatsakis work on anything Javascript related anymore, and there were no champion takers for this proposal.
